-- PDI/PDP — Fase 0: camada de catálogo (aditivo; não altera tabelas existentes)
-- Fonte: PDP 2026 V3 (DNA pág.8, régua pág.4/Anexo3, QCRJ pág.16, matriz skills págs.17-20)

CREATE TABLE IF NOT EXISTS people.pdi_carreiras (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL,
  codigo varchar NOT NULL, nome varchar NOT NULL, ordem int, ativo boolean NOT NULL DEFAULT true,
  UNIQUE (tenant_id, codigo));

CREATE TABLE IF NOT EXISTS people.pdi_faixas_avaliacao (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL,
  codigo varchar NOT NULL, rotulo varchar NOT NULL, ordem int NOT NULL,
  progride boolean NOT NULL DEFAULT false, bonus_pdi boolean NOT NULL DEFAULT false,
  plr_plus_elegivel boolean NOT NULL DEFAULT false, reflexo text,
  UNIQUE (tenant_id, codigo));

CREATE TABLE IF NOT EXISTS people.pdi_pilares (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL,
  trilha varchar NOT NULL, numero int NOT NULL, nome varchar NOT NULL,
  UNIQUE (tenant_id, trilha, numero));

CREATE TABLE IF NOT EXISTS people.pdi_dna_itens (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL,
  numero int NOT NULL, nome varchar NOT NULL, descricao text,
  UNIQUE (tenant_id, numero));

CREATE TABLE IF NOT EXISTS people.pdi_skills_catalogo (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL,
  trilha varchar NOT NULL, pilar_numero int NOT NULL, nivel_codigo varchar NOT NULL,
  item_codigo varchar NOT NULL DEFAULT '', titulo varchar, descricao text, ordem int,
  UNIQUE (tenant_id, trilha, pilar_numero, nivel_codigo, item_codigo));

CREATE TABLE IF NOT EXISTS people.pdi_quadro_remuneracao (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL,
  carreira_codigo varchar NOT NULL, cargo_codigo varchar NOT NULL, coluna varchar NOT NULL,
  salario numeric(12,2), observacao text,
  UNIQUE (tenant_id, carreira_codigo, cargo_codigo, coluna));

INSERT INTO people.pdi_carreiras (tenant_id,codigo,nome,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONTENCIOSO','Contencioso',1) ON CONFLICT (tenant_id,codigo) DO UPDATE SET nome=EXCLUDED.nome, ordem=EXCLUDED.ordem;
INSERT INTO people.pdi_carreiras (tenant_id,codigo,nome,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONSULTORIA','Consultoria',2) ON CONFLICT (tenant_id,codigo) DO UPDATE SET nome=EXCLUDED.nome, ordem=EXCLUDED.ordem;
INSERT INTO people.pdi_carreiras (tenant_id,codigo,nome,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','PLUS','Plus — Estratégico / Liderança',3) ON CONFLICT (tenant_id,codigo) DO UPDATE SET nome=EXCLUDED.nome, ordem=EXCLUDED.ordem;
INSERT INTO people.pdi_carreiras (tenant_id,codigo,nome,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','JR_PARTNER','Jr. Partner',4) ON CONFLICT (tenant_id,codigo) DO UPDATE SET nome=EXCLUDED.nome, ordem=EXCLUDED.ordem;
INSERT INTO people.pdi_carreiras (tenant_id,codigo,nome,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','ADM_FIN','Administrativo e Financeiro',5) ON CONFLICT (tenant_id,codigo) DO UPDATE SET nome=EXCLUDED.nome, ordem=EXCLUDED.ordem;

INSERT INTO people.pdi_faixas_avaliacao (tenant_id,codigo,rotulo,ordem,progride,bonus_pdi,plr_plus_elegivel,reflexo) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','baixa_performance','Baixa performance',1,false,false,false,'Não progride; não tem Bônus PDI') ON CONFLICT (tenant_id,codigo) DO UPDATE SET rotulo=EXCLUDED.rotulo,ordem=EXCLUDED.ordem,progride=EXCLUDED.progride,bonus_pdi=EXCLUDED.bonus_pdi,plr_plus_elegivel=EXCLUDED.plr_plus_elegivel,reflexo=EXCLUDED.reflexo;
INSERT INTO people.pdi_faixas_avaliacao (tenant_id,codigo,rotulo,ordem,progride,bonus_pdi,plr_plus_elegivel,reflexo) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','a_melhorar','A melhorar',2,false,false,false,'Não progride; não tem Bônus PDI') ON CONFLICT (tenant_id,codigo) DO UPDATE SET rotulo=EXCLUDED.rotulo,ordem=EXCLUDED.ordem,progride=EXCLUDED.progride,bonus_pdi=EXCLUDED.bonus_pdi,plr_plus_elegivel=EXCLUDED.plr_plus_elegivel,reflexo=EXCLUDED.reflexo;
INSERT INTO people.pdi_faixas_avaliacao (tenant_id,codigo,rotulo,ordem,progride,bonus_pdi,plr_plus_elegivel,reflexo) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','dentro_da_media','Dentro da média',3,true,false,false,'Progride') ON CONFLICT (tenant_id,codigo) DO UPDATE SET rotulo=EXCLUDED.rotulo,ordem=EXCLUDED.ordem,progride=EXCLUDED.progride,bonus_pdi=EXCLUDED.bonus_pdi,plr_plus_elegivel=EXCLUDED.plr_plus_elegivel,reflexo=EXCLUDED.reflexo;
INSERT INTO people.pdi_faixas_avaliacao (tenant_id,codigo,rotulo,ordem,progride,bonus_pdi,plr_plus_elegivel,reflexo) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','acima_do_esperado','Acima do esperado',4,true,true,false,'Progride + Bônus PDI 100%') ON CONFLICT (tenant_id,codigo) DO UPDATE SET rotulo=EXCLUDED.rotulo,ordem=EXCLUDED.ordem,progride=EXCLUDED.progride,bonus_pdi=EXCLUDED.bonus_pdi,plr_plus_elegivel=EXCLUDED.plr_plus_elegivel,reflexo=EXCLUDED.reflexo;
INSERT INTO people.pdi_faixas_avaliacao (tenant_id,codigo,rotulo,ordem,progride,bonus_pdi,plr_plus_elegivel,reflexo) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','fora_da_curva','Fora da curva',5,true,true,true,'Progride + Bônus PDI 100% + elegível ao PLR Plus') ON CONFLICT (tenant_id,codigo) DO UPDATE SET rotulo=EXCLUDED.rotulo,ordem=EXCLUDED.ordem,progride=EXCLUDED.progride,bonus_pdi=EXCLUDED.bonus_pdi,plr_plus_elegivel=EXCLUDED.plr_plus_elegivel,reflexo=EXCLUDED.reflexo;

INSERT INTO people.pdi_dna_itens (tenant_id,numero,nome) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210',1,'Cabeça de advogado + empresário') ON CONFLICT (tenant_id,numero) DO UPDATE SET nome=EXCLUDED.nome;
INSERT INTO people.pdi_dna_itens (tenant_id,numero,nome) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210',2,'Obstinação pelos clientes') ON CONFLICT (tenant_id,numero) DO UPDATE SET nome=EXCLUDED.nome;
INSERT INTO people.pdi_dna_itens (tenant_id,numero,nome) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210',3,'Time de primeira liga') ON CONFLICT (tenant_id,numero) DO UPDATE SET nome=EXCLUDED.nome;
INSERT INTO people.pdi_dna_itens (tenant_id,numero,nome) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210',4,'Comunicação honesta e direta') ON CONFLICT (tenant_id,numero) DO UPDATE SET nome=EXCLUDED.nome;
INSERT INTO people.pdi_dna_itens (tenant_id,numero,nome) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210',5,'Atitude de protagonista') ON CONFLICT (tenant_id,numero) DO UPDATE SET nome=EXCLUDED.nome;
INSERT INTO people.pdi_dna_itens (tenant_id,numero,nome) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210',6,'Frugalidade e Sofisticação') ON CONFLICT (tenant_id,numero) DO UPDATE SET nome=EXCLUDED.nome;

INSERT INTO people.pdi_pilares (tenant_id,trilha,numero,nome) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','base',1,'Gestão') ON CONFLICT (tenant_id,trilha,numero) DO UPDATE SET nome=EXCLUDED.nome;
INSERT INTO people.pdi_pilares (tenant_id,trilha,numero,nome) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','base',2,'Técnica e performance') ON CONFLICT (tenant_id,trilha,numero) DO UPDATE SET nome=EXCLUDED.nome;
INSERT INTO people.pdi_pilares (tenant_id,trilha,numero,nome) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','base',3,'Autonomia') ON CONFLICT (tenant_id,trilha,numero) DO UPDATE SET nome=EXCLUDED.nome;
INSERT INTO people.pdi_pilares (tenant_id,trilha,numero,nome) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','base',4,'Comportamento') ON CONFLICT (tenant_id,trilha,numero) DO UPDATE SET nome=EXCLUDED.nome;
INSERT INTO people.pdi_pilares (tenant_id,trilha,numero,nome) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','base',5,'Alinhamento') ON CONFLICT (tenant_id,trilha,numero) DO UPDATE SET nome=EXCLUDED.nome;
INSERT INTO people.pdi_pilares (tenant_id,trilha,numero,nome) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','lideranca',6,'Gestão de projetos') ON CONFLICT (tenant_id,trilha,numero) DO UPDATE SET nome=EXCLUDED.nome;
INSERT INTO people.pdi_pilares (tenant_id,trilha,numero,nome) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','lideranca',7,'Alta performance coletiva') ON CONFLICT (tenant_id,trilha,numero) DO UPDATE SET nome=EXCLUDED.nome;
INSERT INTO people.pdi_pilares (tenant_id,trilha,numero,nome) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','lideranca',8,'Liderança e mentoring') ON CONFLICT (tenant_id,trilha,numero) DO UPDATE SET nome=EXCLUDED.nome;
INSERT INTO people.pdi_pilares (tenant_id,trilha,numero,nome) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','estrategico',6,'Gestão de projetos estratégicos') ON CONFLICT (tenant_id,trilha,numero) DO UPDATE SET nome=EXCLUDED.nome;
INSERT INTO people.pdi_pilares (tenant_id,trilha,numero,nome) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','estrategico',7,'Técnica superior, interface direta e multidisciplinaridade') ON CONFLICT (tenant_id,trilha,numero) DO UPDATE SET nome=EXCLUDED.nome;
INSERT INTO people.pdi_pilares (tenant_id,trilha,numero,nome) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','estrategico',8,'Jogo de cintura e performance diferenciada') ON CONFLICT (tenant_id,trilha,numero) DO UPDATE SET nome=EXCLUDED.nome;

INSERT INTO people.pdi_skills_catalogo (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo,titulo,descricao,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','base',1,'ESTAGIARIO','','Aprender o valor da gestão do tempo',NULL,1) ON CONFLICT (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo) DO UPDATE SET titulo=EXCLUDED.titulo,descricao=EXCLUDED.descricao,ordem=EXCLUDED.ordem;
INSERT INTO people.pdi_skills_catalogo (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo,titulo,descricao,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','base',1,'JUNIOR','1.1','Gestão do seu tempo e das suas tarefas','Gere com eficiência e eficácia seu tempo e sabe priorizar as suas tarefas de modo a otimizar sua produtividade',2) ON CONFLICT (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo) DO UPDATE SET titulo=EXCLUDED.titulo,descricao=EXCLUDED.descricao,ordem=EXCLUDED.ordem;
INSERT INTO people.pdi_skills_catalogo (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo,titulo,descricao,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','base',1,'PLENO','1.1','Gestão do seu tempo e projetos','Gere com eficiência e eficácia suas tarefas e projetos e conduz',3) ON CONFLICT (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo) DO UPDATE SET titulo=EXCLUDED.titulo,descricao=EXCLUDED.descricao,ordem=EXCLUDED.ordem;
INSERT INTO people.pdi_skills_catalogo (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo,titulo,descricao,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','base',1,'SENIOR','1.1','Gestão de risco e oportunidades','Sabe se antecipar aos problemas emergentes e constrói medidas de gestão de risco para mitigar as consequências',4) ON CONFLICT (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo) DO UPDATE SET titulo=EXCLUDED.titulo,descricao=EXCLUDED.descricao,ordem=EXCLUDED.ordem;
INSERT INTO people.pdi_skills_catalogo (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo,titulo,descricao,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','base',1,'SENIOR','1.2','Gestão de risco e oportunidades','Gere com eficiência e eficácia projetos e casos de alta complexidade',5) ON CONFLICT (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo) DO UPDATE SET titulo=EXCLUDED.titulo,descricao=EXCLUDED.descricao,ordem=EXCLUDED.ordem;
INSERT INTO people.pdi_skills_catalogo (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo,titulo,descricao,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','base',2,'ESTAGIARIO','','Foco, atenção e qualidade',NULL,6) ON CONFLICT (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo) DO UPDATE SET titulo=EXCLUDED.titulo,descricao=EXCLUDED.descricao,ordem=EXCLUDED.ordem;
INSERT INTO people.pdi_skills_catalogo (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo,titulo,descricao,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','base',2,'JUNIOR','2.1','Pesquisa, redação e elaboração','Faz pesquisas com racional jurídico apurado',7) ON CONFLICT (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo) DO UPDATE SET titulo=EXCLUDED.titulo,descricao=EXCLUDED.descricao,ordem=EXCLUDED.ordem;
INSERT INTO people.pdi_skills_catalogo (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo,titulo,descricao,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','base',2,'JUNIOR','2.2','Pesquisa, redação e elaboração','Elabora e analisa de forma assertiva documentos de baixa complexidade',8) ON CONFLICT (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo) DO UPDATE SET titulo=EXCLUDED.titulo,descricao=EXCLUDED.descricao,ordem=EXCLUDED.ordem;
INSERT INTO people.pdi_skills_catalogo (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo,titulo,descricao,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','base',2,'JUNIOR','2.3','Pesquisa, redação e elaboração','Elabora e analisa de forma inicial documentos de média complexidade',9) ON CONFLICT (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo) DO UPDATE SET titulo=EXCLUDED.titulo,descricao=EXCLUDED.descricao,ordem=EXCLUDED.ordem;
INSERT INTO people.pdi_skills_catalogo (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo,titulo,descricao,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','base',2,'JUNIOR','2.4','Pesquisa, redação e elaboração','Tem qualidade no atendimento inicial ao cliente',10) ON CONFLICT (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo) DO UPDATE SET titulo=EXCLUDED.titulo,descricao=EXCLUDED.descricao,ordem=EXCLUDED.ordem;
INSERT INTO people.pdi_skills_catalogo (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo,titulo,descricao,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','base',2,'PLENO','2.1','Excelência na entrega','Faz pesquisas conclusivas',11) ON CONFLICT (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo) DO UPDATE SET titulo=EXCLUDED.titulo,descricao=EXCLUDED.descricao,ordem=EXCLUDED.ordem;
INSERT INTO people.pdi_skills_catalogo (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo,titulo,descricao,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','base',2,'PLENO','2.2','Excelência na entrega','Revisa de forma resolutiva documentos de baixa complexidade',12) ON CONFLICT (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo) DO UPDATE SET titulo=EXCLUDED.titulo,descricao=EXCLUDED.descricao,ordem=EXCLUDED.ordem;
INSERT INTO people.pdi_skills_catalogo (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo,titulo,descricao,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','base',2,'PLENO','2.3','Excelência na entrega','Elabora e revisa assertivamente documentos de média complexidade',13) ON CONFLICT (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo) DO UPDATE SET titulo=EXCLUDED.titulo,descricao=EXCLUDED.descricao,ordem=EXCLUDED.ordem;
INSERT INTO people.pdi_skills_catalogo (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo,titulo,descricao,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','base',2,'PLENO','2.4','Excelência na entrega','Elabora e analisa de forma inicial documentos de alta complexidade',14) ON CONFLICT (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo) DO UPDATE SET titulo=EXCLUDED.titulo,descricao=EXCLUDED.descricao,ordem=EXCLUDED.ordem;
INSERT INTO people.pdi_skills_catalogo (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo,titulo,descricao,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','base',2,'PLENO','2.5','Excelência na entrega','Tem senso crítico para ponderar, questionar ou direcionar as solicitações do cliente de forma assertiva',15) ON CONFLICT (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo) DO UPDATE SET titulo=EXCLUDED.titulo,descricao=EXCLUDED.descricao,ordem=EXCLUDED.ordem;
INSERT INTO people.pdi_skills_catalogo (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo,titulo,descricao,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','base',2,'SENIOR','2.1','Alta performance','Faz pesquisas resolutivas, desenvolvendo alternativas jurídicas para mitigar o risco e maximizar o ganho nas demandas',16) ON CONFLICT (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo) DO UPDATE SET titulo=EXCLUDED.titulo,descricao=EXCLUDED.descricao,ordem=EXCLUDED.ordem;
INSERT INTO people.pdi_skills_catalogo (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo,titulo,descricao,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','base',2,'SENIOR','2.2','Alta performance','Elabora e revisa de forma resolutiva documentos de média e alta complexidade',17) ON CONFLICT (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo) DO UPDATE SET titulo=EXCLUDED.titulo,descricao=EXCLUDED.descricao,ordem=EXCLUDED.ordem;
INSERT INTO people.pdi_skills_catalogo (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo,titulo,descricao,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','base',2,'SENIOR','2.3','Alta performance','Tem uma performance baseada na capacidade de entregar com volume e consistência técnica e temporal',18) ON CONFLICT (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo) DO UPDATE SET titulo=EXCLUDED.titulo,descricao=EXCLUDED.descricao,ordem=EXCLUDED.ordem;
INSERT INTO people.pdi_skills_catalogo (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo,titulo,descricao,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','base',2,'SENIOR','2.4','Alta performance','Tem atendimento altamente resolutivo ao cliente e consegue entregar resultados de alto impacto',19) ON CONFLICT (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo) DO UPDATE SET titulo=EXCLUDED.titulo,descricao=EXCLUDED.descricao,ordem=EXCLUDED.ordem;
INSERT INTO people.pdi_skills_catalogo (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo,titulo,descricao,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','base',3,'ESTAGIARIO','','Curiosidade e humildade para aprender',NULL,20) ON CONFLICT (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo) DO UPDATE SET titulo=EXCLUDED.titulo,descricao=EXCLUDED.descricao,ordem=EXCLUDED.ordem;
INSERT INTO people.pdi_skills_catalogo (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo,titulo,descricao,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','base',3,'JUNIOR','3.1','Autodesenvolvimento e Resolução de problemas','Evolui continuamente na técnica e operação dentro da sua área jurídica',21) ON CONFLICT (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo) DO UPDATE SET titulo=EXCLUDED.titulo,descricao=EXCLUDED.descricao,ordem=EXCLUDED.ordem;
INSERT INTO people.pdi_skills_catalogo (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo,titulo,descricao,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','base',3,'JUNIOR','3.2','Autodesenvolvimento e Resolução de problemas','Consegue buscar respostas para os desafios do dia a dia por conta própria, mas busca a validação de algum advogado mais experiente sempre que necessário',22) ON CONFLICT (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo) DO UPDATE SET titulo=EXCLUDED.titulo,descricao=EXCLUDED.descricao,ordem=EXCLUDED.ordem;
INSERT INTO people.pdi_skills_catalogo (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo,titulo,descricao,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','base',3,'PLENO','3.1','Autonomia e Resolução de problemas','Tem autonomia para realizar as entregas corriqueiras com o cliente, sempre com respaldo técnico',23) ON CONFLICT (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo) DO UPDATE SET titulo=EXCLUDED.titulo,descricao=EXCLUDED.descricao,ordem=EXCLUDED.ordem;
INSERT INTO people.pdi_skills_catalogo (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo,titulo,descricao,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','base',3,'PLENO','3.2','Autonomia e Resolução de problemas','Consegue resolver problemas mais complexos e buscar alternativas de forma dinâmica e proativa, sempre se aconselhando com um par',24) ON CONFLICT (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo) DO UPDATE SET titulo=EXCLUDED.titulo,descricao=EXCLUDED.descricao,ordem=EXCLUDED.ordem;
INSERT INTO people.pdi_skills_catalogo (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo,titulo,descricao,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','base',3,'SENIOR','3.1','Independência e autorresponsabilidade','Tem senso crítico afinado e consegue articular soluções complexas, interna e externamente, de forma autônoma e independente, acionando o seu par sênior ou sócio apenas quando necessário',25) ON CONFLICT (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo) DO UPDATE SET titulo=EXCLUDED.titulo,descricao=EXCLUDED.descricao,ordem=EXCLUDED.ordem;
INSERT INTO people.pdi_skills_catalogo (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo,titulo,descricao,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','base',3,'SENIOR','3.2','Independência e autorresponsabilidade','É responsável por aquilo que você decide para si e pelo cliente; tem capacidade de sustentar o racional das suas decisões',26) ON CONFLICT (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo) DO UPDATE SET titulo=EXCLUDED.titulo,descricao=EXCLUDED.descricao,ordem=EXCLUDED.ordem;
INSERT INTO people.pdi_skills_catalogo (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo,titulo,descricao,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','base',4,'ESTAGIARIO','','Ser uma pessoa flexível',NULL,27) ON CONFLICT (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo) DO UPDATE SET titulo=EXCLUDED.titulo,descricao=EXCLUDED.descricao,ordem=EXCLUDED.ordem;
INSERT INTO people.pdi_skills_catalogo (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo,titulo,descricao,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','base',4,'JUNIOR','4.1','Comunicação e colaboração','Tem comunicação verbal e escrita assertiva adequada ao cliente interno e externo',28) ON CONFLICT (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo) DO UPDATE SET titulo=EXCLUDED.titulo,descricao=EXCLUDED.descricao,ordem=EXCLUDED.ordem;
INSERT INTO people.pdi_skills_catalogo (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo,titulo,descricao,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','base',4,'JUNIOR','4.2','Comunicação e colaboração','Sabe trabalhar em grupo, ajuda a treinar os estagiários e interage e colabora com as outras pessoas sempre que necessário',29) ON CONFLICT (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo) DO UPDATE SET titulo=EXCLUDED.titulo,descricao=EXCLUDED.descricao,ordem=EXCLUDED.ordem;
INSERT INTO people.pdi_skills_catalogo (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo,titulo,descricao,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','base',4,'JUNIOR','4.3','Comunicação e colaboração','Demonstra abertura a novos desafios e se adapta bem à mudança de cenários',30) ON CONFLICT (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo) DO UPDATE SET titulo=EXCLUDED.titulo,descricao=EXCLUDED.descricao,ordem=EXCLUDED.ordem;
INSERT INTO people.pdi_skills_catalogo (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo,titulo,descricao,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','base',4,'PLENO','4.1','Colaboração e autorresponsabilidade','Treina de forma estruturada os profissionais Júnior, sabe trabalhar em grupo, interagindo e colaborando com as outras pessoas e áreas sempre que necessário',31) ON CONFLICT (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo) DO UPDATE SET titulo=EXCLUDED.titulo,descricao=EXCLUDED.descricao,ordem=EXCLUDED.ordem;
INSERT INTO people.pdi_skills_catalogo (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo,titulo,descricao,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','base',4,'PLENO','4.2','Colaboração e autorresponsabilidade','Tem curiosidade e criatividade para explorar novos temas e conhecimentos dentro e fora da sua área de atuação',32) ON CONFLICT (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo) DO UPDATE SET titulo=EXCLUDED.titulo,descricao=EXCLUDED.descricao,ordem=EXCLUDED.ordem;
INSERT INTO people.pdi_skills_catalogo (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo,titulo,descricao,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','base',4,'SENIOR','4.1','Relacionamento e influência','Tem influência no sistema que está inserido, consegue engajar outras pessoas e construir objetivos ao redor de uma visão compartilhada no time',33) ON CONFLICT (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo) DO UPDATE SET titulo=EXCLUDED.titulo,descricao=EXCLUDED.descricao,ordem=EXCLUDED.ordem;
INSERT INTO people.pdi_skills_catalogo (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo,titulo,descricao,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','base',4,'SENIOR','4.2','Relacionamento e influência','Tem inteligência emocional e pragmatismo para lidar com problemas dentro da esfera técnica',34) ON CONFLICT (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo) DO UPDATE SET titulo=EXCLUDED.titulo,descricao=EXCLUDED.descricao,ordem=EXCLUDED.ordem;
INSERT INTO people.pdi_skills_catalogo (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo,titulo,descricao,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','base',4,'SENIOR','4.3','Relacionamento e influência','Mantém relacionamentos duradouros com os clientes e parceiros e consegue sustentar a rede de negócios por meio deles',35) ON CONFLICT (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo) DO UPDATE SET titulo=EXCLUDED.titulo,descricao=EXCLUDED.descricao,ordem=EXCLUDED.ordem;
INSERT INTO people.pdi_skills_catalogo (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo,titulo,descricao,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','base',5,'ESTAGIARIO','','Aprender a colaborar',NULL,36) ON CONFLICT (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo) DO UPDATE SET titulo=EXCLUDED.titulo,descricao=EXCLUDED.descricao,ordem=EXCLUDED.ordem;
INSERT INTO people.pdi_skills_catalogo (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo,titulo,descricao,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','base',5,'JUNIOR','5.1','Fit cultural','É aderente ao DNA VLMA e com a ética de trabalho do escritório',37) ON CONFLICT (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo) DO UPDATE SET titulo=EXCLUDED.titulo,descricao=EXCLUDED.descricao,ordem=EXCLUDED.ordem;
INSERT INTO people.pdi_skills_catalogo (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo,titulo,descricao,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','base',5,'PLENO','5.1','Fit estratégico','Tem alinhamento com a estratégia macro do escritório e da sua área',38) ON CONFLICT (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo) DO UPDATE SET titulo=EXCLUDED.titulo,descricao=EXCLUDED.descricao,ordem=EXCLUDED.ordem;
INSERT INTO people.pdi_skills_catalogo (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo,titulo,descricao,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','base',5,'SENIOR','5.1','Pensamento estratégico','Entende o negócio da sua área e do escritório e desenvolve estratégias de crescimento e melhoria contínua de performance',39) ON CONFLICT (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo) DO UPDATE SET titulo=EXCLUDED.titulo,descricao=EXCLUDED.descricao,ordem=EXCLUDED.ordem;
INSERT INTO people.pdi_skills_catalogo (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo,titulo,descricao,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','lideranca',6,'TODOS','6.1','Gestão de projetos','Habilidade de gerir demandas simultâneas suas e de sua equipe na sua área e com outras',40) ON CONFLICT (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo) DO UPDATE SET titulo=EXCLUDED.titulo,descricao=EXCLUDED.descricao,ordem=EXCLUDED.ordem;
INSERT INTO people.pdi_skills_catalogo (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo,titulo,descricao,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','lideranca',7,'TODOS','7.1','Alta performance coletiva','Consegue extrair a melhor performance profissional de cada pessoa e obtém resultados coletivos para a sua área e escritório',41) ON CONFLICT (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo) DO UPDATE SET titulo=EXCLUDED.titulo,descricao=EXCLUDED.descricao,ordem=EXCLUDED.ordem;
INSERT INTO people.pdi_skills_catalogo (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo,titulo,descricao,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','lideranca',8,'TODOS','8.1','Liderança e mentoring','Lidera de forma empática, pelo exemplo e auxilia outras pessoas a se desenvolverem por meio do coaching (aconselhamento) e mentoring (mentoria)',42) ON CONFLICT (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo) DO UPDATE SET titulo=EXCLUDED.titulo,descricao=EXCLUDED.descricao,ordem=EXCLUDED.ordem;
INSERT INTO people.pdi_skills_catalogo (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo,titulo,descricao,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','estrategico',6,'TODOS','6.1','Gestão de projetos estratégicos','Habilidade de gerir projetos complexos, multidisciplinares e colaborativos com outras áreas e clientes',43) ON CONFLICT (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo) DO UPDATE SET titulo=EXCLUDED.titulo,descricao=EXCLUDED.descricao,ordem=EXCLUDED.ordem;
INSERT INTO people.pdi_skills_catalogo (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo,titulo,descricao,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','estrategico',7,'TODOS','7.1','Técnica superior, interface direta e multidisciplinaridade','Entrega com maestria (consistência e previsibilidade), técnica superior (repertório), agilidade (dinamismo e adaptabilidade) e responsividade (rapidez e comunicação assertiva)',44) ON CONFLICT (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo) DO UPDATE SET titulo=EXCLUDED.titulo,descricao=EXCLUDED.descricao,ordem=EXCLUDED.ordem;
INSERT INTO people.pdi_skills_catalogo (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo,titulo,descricao,ordem) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','estrategico',8,'TODOS','8.1','Jogo de cintura e performance diferenciada','Tem jogo de cintura e adaptabilidade, criatividade e alta habilidade na resolução de problemas complexos',45) ON CONFLICT (tenant_id,trilha,pilar_numero,nivel_codigo,item_codigo) DO UPDATE SET titulo=EXCLUDED.titulo,descricao=EXCLUDED.descricao,ordem=EXCLUDED.ordem;

INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONTENCIOSO','JR1','I',4000.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONTENCIOSO','JR2','I',4300.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONTENCIOSO','JR3','I',4700.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONTENCIOSO','JR4','I',5100.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONTENCIOSO','JR5','I',5500.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONTENCIOSO','PL1','I',6000.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONTENCIOSO','PL1','T_10',6600.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONTENCIOSO','PL1','T_20',7200.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONTENCIOSO','PL2','I',6500.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONTENCIOSO','PL2','T_10',7150.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONTENCIOSO','PL2','T_20',7800.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONTENCIOSO','PL3','I',7000.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONTENCIOSO','PL3','T_10',7700.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONTENCIOSO','PL3','T_20',8400.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONTENCIOSO','PL4','I',7600.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONTENCIOSO','PL4','T_10',8360.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONTENCIOSO','PL4','T_20',9120.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONTENCIOSO','PL5','I',8200.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONTENCIOSO','PL5','T_10',9020.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONTENCIOSO','PL5','T_20',9840.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONTENCIOSO','SR1','I',8900.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONTENCIOSO','SR1','T_10',9790.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONTENCIOSO','SR1','T_20',10680.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONTENCIOSO','SR2','I',9600.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONTENCIOSO','SR2','T_10',10560.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONTENCIOSO','SR2','T_20',11520.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONTENCIOSO','SR3','I',10300.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONTENCIOSO','SR3','T_10',11330.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONTENCIOSO','SR3','T_20',12360.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONTENCIOSO','SR4','I',11500.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONTENCIOSO','SR4','T_10',12650.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONTENCIOSO','SR4','T_20',13800.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONTENCIOSO','SR5','I',12420.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONTENCIOSO','SR5','T_10',13662.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONTENCIOSO','SR5','T_20',14900.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONTENCIOSO','SR6','I',13420.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONTENCIOSO','SR6','T_10',14780.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONTENCIOSO','SR6','T_20',16100.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONTENCIOSO','SR7','I',14500.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONTENCIOSO','SR7','T_10',15950.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONTENCIOSO','SR7','T_20',17400.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONTENCIOSO','SR8','I',15650.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONTENCIOSO','SR8','T_10',17210.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONTENCIOSO','SR8','T_20',18780.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONSULTORIA','JR1','I',4300.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONSULTORIA','JR2','I',4720.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONSULTORIA','JR3','I',5000.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONSULTORIA','JR4','I',5400.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONSULTORIA','JR5','I',5900.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONSULTORIA','PL1','I',6500.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONSULTORIA','PL1','T_10',7150.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONSULTORIA','PL1','T_20',7800.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONSULTORIA','PL2','I',7000.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONSULTORIA','PL2','T_10',7700.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONSULTORIA','PL2','T_20',8400.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONSULTORIA','PL3','I',7600.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONSULTORIA','PL3','T_10',8360.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONSULTORIA','PL3','T_20',9120.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONSULTORIA','PL4','I',8200.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONSULTORIA','PL4','T_10',9020.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONSULTORIA','PL4','T_20',9840.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONSULTORIA','PL5','I',8900.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONSULTORIA','PL5','T_10',9790.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONSULTORIA','PL5','T_20',10680.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONSULTORIA','SR1','I',9600.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONSULTORIA','SR1','T_10',10560.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONSULTORIA','SR1','T_20',11520.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONSULTORIA','SR2','I',10300.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONSULTORIA','SR2','T_10',11330.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONSULTORIA','SR2','T_20',12360.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONSULTORIA','SR3','I',11200.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONSULTORIA','SR3','T_10',12320.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONSULTORIA','SR3','T_20',13440.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONSULTORIA','SR4','I',12100.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONSULTORIA','SR4','T_10',13550.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONSULTORIA','SR4','T_20',15000.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONSULTORIA','SR5','I',13070.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONSULTORIA','SR5','T_10',14375.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONSULTORIA','SR5','T_20',15685.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONSULTORIA','SR6','I',14120.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONSULTORIA','SR6','T_10',15525.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONSULTORIA','SR6','T_20',16940.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONSULTORIA','SR7','I',15250.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONSULTORIA','SR7','T_10',16770.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONSULTORIA','SR7','T_20',18300.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONSULTORIA','SR8','I',16470.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONSULTORIA','SR8','T_10',18110.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONSULTORIA','SR8','T_20',19755.00,NULL) ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONTENCIOSO','ESTAG1','I',1500.00,'Bolsa auxílio 1º ano + R$200 auxílio transporte') ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario,observacao=EXCLUDED.observacao;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONTENCIOSO','ESTAG2','I',1800.00,'Bolsa auxílio 2º ano + R$200 auxílio transporte') ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario,observacao=EXCLUDED.observacao;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONSULTORIA','ESTAG1','I',1500.00,'Bolsa auxílio 1º ano + R$200 auxílio transporte') ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario,observacao=EXCLUDED.observacao;
INSERT INTO people.pdi_quadro_remuneracao (tenant_id,carreira_codigo,cargo_codigo,coluna,salario,observacao) VALUES ('d51463dd-a6b3-40e7-9488-854eba80a210','CONSULTORIA','ESTAG2','I',1800.00,'Bolsa auxílio 2º ano + R$200 auxílio transporte') ON CONFLICT (tenant_id,carreira_codigo,cargo_codigo,coluna) DO UPDATE SET salario=EXCLUDED.salario,observacao=EXCLUDED.observacao;

CREATE OR REPLACE FUNCTION public.get_pdi_catalogo()
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, people, core AS $function$
DECLARE v_tenant uuid;
BEGIN
  SELECT tenant_id INTO v_tenant FROM core.tenant_users WHERE user_id = auth.uid() AND status = 'ativo' LIMIT 1;
  IF v_tenant IS NULL THEN RAISE EXCEPTION 'Usuário não associado a tenant'; END IF;
  RETURN jsonb_build_object(
    'carreiras', (SELECT COALESCE(jsonb_agg(to_jsonb(c) ORDER BY c.ordem),'[]'::jsonb) FROM people.pdi_carreiras c WHERE c.tenant_id=v_tenant AND c.ativo),
    'regua', (SELECT COALESCE(jsonb_agg(to_jsonb(f) ORDER BY f.ordem),'[]'::jsonb) FROM people.pdi_faixas_avaliacao f WHERE f.tenant_id=v_tenant),
    'pilares', (SELECT COALESCE(jsonb_agg(to_jsonb(p) ORDER BY p.trilha,p.numero),'[]'::jsonb) FROM people.pdi_pilares p WHERE p.tenant_id=v_tenant),
    'dna', (SELECT COALESCE(jsonb_agg(to_jsonb(d) ORDER BY d.numero),'[]'::jsonb) FROM people.pdi_dna_itens d WHERE d.tenant_id=v_tenant),
    'skills', (SELECT COALESCE(jsonb_agg(to_jsonb(s) ORDER BY s.trilha,s.pilar_numero,s.nivel_codigo,s.item_codigo),'[]'::jsonb) FROM people.pdi_skills_catalogo s WHERE s.tenant_id=v_tenant),
    'quadro_remuneracao', (SELECT COALESCE(jsonb_agg(to_jsonb(q) ORDER BY q.carreira_codigo,q.cargo_codigo,q.coluna),'[]'::jsonb) FROM people.pdi_quadro_remuneracao q WHERE q.tenant_id=v_tenant)
  );
END;
$function$;
GRANT EXECUTE ON FUNCTION public.get_pdi_catalogo() TO authenticated;
